project:
  type: website
  output-dir: docs

website:
  title: "[Mustafa Alp Ulas]'s Analytics Lab"
  navbar:
    background: "dark"
    foreground: "light"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/mustafalpulaslab
      - icon: twitter
        href: https://x.com/MustafaAlpUla1
      - icon: linkedin
        href: https://www.linkedin.com/in/mustafaalpulas

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU430 - 2024 Fall" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: sketchy
    css: styles.css


editor: visual

