---
title: "My Summary"
sidebar: false 
---

**Hi! My name is Mustafa Alp. I am junior at Hacettepe University.I am trying to finish my Bachelor's Degree in Industrial Engineering. I like playing football. When I was a child, I was playing football in local team which is Akdeniz Timsahlari in Alanya. This team is a pilot team of Bursa Spor Football Club. Also, I like playing table tennis, Professor Dr. Murat Caner TESTIK confirms that I play table tennis well :). In addition, I am interested in biking but extreme one. It is called "Downhill" or "Urban Downhill". I like playing online games which are fps games on pc. I am a pc gamer by the way. If the subject is industrial engineering, I love Industrial Engineering. When I was 10 years old, I decided that I would become an industrial engineer when I grew up. So that, I chose Industrial Engineering English program of Hacettepe University. I loved Operation Research and Programming Application. But I can say that, I don't like Probability and Statistic Topics. But I have to know. This is my summary in briefly. Have a nice day :)**
